# Generated by Django 5.2.11 on 2026-02-26 08:59

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModalSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("CAR", "Private Car"),
                            ("MCY", "Motorcycle"),
                            ("PUB", "Public Transit"),
                            ("EHL", "E-Hailing"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "share_pct",
                    models.FloatField(help_text="Percentage share of total trips"),
                ),
                ("avg_occupancy", models.FloatField(default=1.0)),
                (
                    "co2_grams_per_km",
                    models.FloatField(help_text="CO2 emission factor"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "map_x",
                    models.FloatField(
                        help_text="Canvas X coord 0-1",
                        validators=[core.validators.validate_coordinate],
                    ),
                ),
                (
                    "map_y",
                    models.FloatField(
                        help_text="Canvas Y coord 0-1",
                        validators=[core.validators.validate_coordinate],
                    ),
                ),
                ("is_major", models.BooleanField(default=False)),
                ("icon", models.CharField(default="house", max_length=20)),
                ("population", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransitLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("LRT", "Light Rail Transit"),
                            ("MRT", "Mass Rapid Transit"),
                            ("BRT", "Bus Rapid Transit"),
                            ("KTM", "KTM Komuter"),
                            ("MNR", "Monorail"),
                            ("BUS", "Bus"),
                        ],
                        max_length=3,
                    ),
                ),
                ("capacity_per_hour", models.PositiveIntegerField()),
                (
                    "frequency_minutes",
                    models.FloatField(help_text="Peak frequency in minutes"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#00d4ff",
                        help_text="Hex color for UI display",
                        max_length=7,
                    ),
                ),
                ("route_description", models.CharField(blank=True, max_length=200)),
                (
                    "zones_served",
                    models.ManyToManyField(
                        blank=True, related_name="transit_lines", to="core.zone"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Corridor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "distance_km",
                    models.FloatField(validators=[core.validators.validate_positive]),
                ),
                (
                    "free_flow_speed_kmh",
                    models.FloatField(validators=[core.validators.validate_positive]),
                ),
                (
                    "capacity_vph",
                    models.PositiveIntegerField(help_text="Vehicles per hour capacity"),
                ),
                ("bpr_alpha", models.FloatField(default=0.15)),
                ("bpr_beta", models.FloatField(default=4.0)),
                ("is_tolled", models.BooleanField(default=False)),
                (
                    "toll_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "daily_volume",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated daily vehicle count"
                    ),
                ),
                (
                    "zone_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corridors_from",
                        to="core.zone",
                    ),
                ),
                (
                    "zone_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corridors_to",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarpoolHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "map_x",
                    models.FloatField(validators=[core.validators.validate_coordinate]),
                ),
                (
                    "map_y",
                    models.FloatField(validators=[core.validators.validate_coordinate]),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(help_text="Max vehicles that can park"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpool_hubs",
                        to="core.zone",
                    ),
                ),
            ],
        ),
    ]
