# Generated by Django 5.2.11 on 2026-02-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("core", "0001_initial"),
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarpoolGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("route_description", models.CharField(blank=True, max_length=200)),
                ("departure_time", models.TimeField()),
                ("max_seats", models.PositiveIntegerField(default=4)),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="core.carpoolhub",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpool_groups",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarpoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("DRV", "Driver"), ("PSG", "Passenger")], max_length=3
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="staff.carpoolgroup",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpool_memberships",
                        to="company.staffmember",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "group")},
            },
        ),
    ]
