# Generated by Django 5.2.11 on 2026-02-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Untitled Run", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("RUN", "Running"),
                            ("CMP", "Completed"),
                            ("ERR", "Error"),
                        ],
                        default="PND",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("enable_stagger", models.BooleanField(default=True)),
                ("enable_wfh", models.BooleanField(default=True)),
                ("enable_carpool", models.BooleanField(default=True)),
                ("enable_transit_boost", models.BooleanField(default=True)),
                ("stagger_window_start", models.TimeField(blank=True, null=True)),
                ("stagger_window_end", models.TimeField(blank=True, null=True)),
                ("wfh_max_days", models.PositiveIntegerField(default=2)),
                (
                    "wfh_sector_cap_pct",
                    models.PositiveIntegerField(
                        default=40, help_text="Max % of any sector WFH same day"
                    ),
                ),
                ("carpool_max_detour_km", models.FloatField(default=5.0)),
                (
                    "transit_frequency_boost_pct",
                    models.PositiveIntegerField(default=20),
                ),
                ("peak_congestion_before", models.FloatField(blank=True, null=True)),
                ("peak_congestion_after", models.FloatField(blank=True, null=True)),
                (
                    "avg_commute_before",
                    models.FloatField(blank=True, help_text="Minutes", null=True),
                ),
                (
                    "avg_commute_after",
                    models.FloatField(blank=True, help_text="Minutes", null=True),
                ),
                (
                    "peak_vehicles_before",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "peak_vehicles_after",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("co2_saved_tonnes", models.FloatField(blank=True, null=True)),
                (
                    "total_carpool_groups",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_wfh_today", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorridorTimeSlice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        help_text="HH:MM format, e.g. 07:30", max_length=5
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("before", "Before (Status Quo)"),
                            ("after", "After (MyCommute Active)"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        default=0, help_text="Total PCE volume"
                    ),
                ),
                ("volume_car", models.PositiveIntegerField(default=0)),
                ("volume_motorcycle", models.PositiveIntegerField(default=0)),
                (
                    "capacity_ratio",
                    models.FloatField(default=0.0, help_text="V/C ratio"),
                ),
                ("travel_time_min", models.FloatField(default=0.0)),
                ("speed_kmh", models.FloatField(default=0.0)),
                (
                    "congestion_level",
                    models.FloatField(default=0.0, help_text="0-1 congestion index"),
                ),
                (
                    "corridor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slices",
                        to="core.corridor",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corridor_slices",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["simulation_run", "corridor", "time_slot", "scenario"],
                "indexes": [
                    models.Index(
                        fields=["simulation_run", "scenario", "time_slot"],
                        name="simulation__simulat_4b205e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanySimResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_start_time", models.TimeField(blank=True, null=True)),
                ("staff_on_road_before", models.PositiveIntegerField(default=0)),
                ("staff_on_road_after", models.PositiveIntegerField(default=0)),
                ("wfh_count", models.PositiveIntegerField(default=0)),
                ("carpool_count", models.PositiveIntegerField(default=0)),
                (
                    "load_contribution",
                    models.FloatField(
                        default=0.0, help_text="0-1 fraction of peak load"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sim_results",
                        to="company.company",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_results",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["simulation_run", "-load_contribution"],
                "unique_together": {("simulation_run", "company")},
            },
        ),
    ]
