# Generated by Django 5.2.11 on 2026-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="workforce_multiplier",
            field=models.FloatField(
                default=1.0,
                help_text="Scale factor applied to company total_staff for simulation (e.g. 1.0 = use as-is, 0.5 = half)",
            ),
        ),
    ]
