# Generated by Django 5.2.11 on 2026-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0002_simulationrun_workforce_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="car_mode_share_pct",
            field=models.FloatField(
                default=67.0, help_text="Percentage of commuters using private car"
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="carpool_willingness_pct",
            field=models.PositiveIntegerField(
                default=35, help_text="Percentage of vehicle owners willing to carpool"
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="motorcycle_mode_share_pct",
            field=models.FloatField(
                default=17.0, help_text="Percentage of commuters using motorcycle"
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="public_transit_share_pct",
            field=models.FloatField(
                default=12.0, help_text="Percentage of commuters using public transit"
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="target_avg_commute_min",
            field=models.FloatField(
                blank=True,
                help_text="Target average commute time in minutes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="target_peak_vehicles",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target peak vehicles on road (auto-scales workforce to match)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="wfh_eligibility_pct",
            field=models.PositiveIntegerField(
                default=80, help_text="Percentage of staff eligible for WFH"
            ),
        ),
        migrations.AlterField(
            model_name="simulationrun",
            name="workforce_multiplier",
            field=models.FloatField(
                default=1.0,
                help_text="Scale factor applied to company total_staff for simulation",
            ),
        ),
    ]
