# Generated by Django 5.2.11 on 2026-05-16 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0003_simulationrun_car_mode_share_pct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationrun",
            name="target_avg_commute_min",
        ),
        migrations.RemoveField(
            model_name="simulationrun",
            name="target_peak_vehicles",
        ),
    ]
