# Generated by Django 5.2.11 on 2026-02-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(help_text="0=Monday, 4=Friday"),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("OFF", "Office"), ("WFH", "Work From Home")],
                        default="OFF",
                        max_length=3,
                    ),
                ),
                ("assigned_start_time", models.TimeField(blank=True, null=True)),
                (
                    "departure_window",
                    models.CharField(
                        blank=True, help_text="e.g. 07:15 - 07:45", max_length=20
                    ),
                ),
                ("estimated_commute_min", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["staff", "day_of_week"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Energy", "Energy"),
                            ("Banking", "Banking"),
                            ("Telecom", "Telecom"),
                            ("Aviation", "Aviation"),
                            ("Conglomerate", "Conglomerate"),
                            ("Media", "Media"),
                            ("Government", "Government"),
                            ("Technology", "Technology"),
                            ("Construction", "Construction"),
                            ("Manufacturing", "Manufacturing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_staff", models.PositiveIntegerField()),
                ("default_start_time", models.TimeField()),
                (
                    "is_glc",
                    models.BooleanField(
                        default=False, help_text="Government-linked company"
                    ),
                ),
                ("wfh_days_per_week", models.PositiveIntegerField(default=1)),
                (
                    "compliance_score",
                    models.FloatField(default=0.0, help_text="0-100 compliance rating"),
                ),
                (
                    "office_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["-total_staff"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("staff_count", models.PositiveIntegerField(default=0)),
                ("can_wfh", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "primary_transport",
                    models.CharField(
                        choices=[
                            ("CAR", "Private Car"),
                            ("MCY", "Motorcycle"),
                            ("PUB", "Public Transit"),
                            ("EHL", "E-Hailing"),
                            ("CPL", "Carpool"),
                        ],
                        default="CAR",
                        max_length=3,
                    ),
                ),
                ("has_vehicle", models.BooleanField(default=True)),
                ("willing_to_carpool", models.BooleanField(default=False)),
                (
                    "carpool_seats",
                    models.PositiveIntegerField(
                        default=0, help_text="Seats offered if driver"
                    ),
                ),
                ("can_wfh", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="company.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="company.department",
                    ),
                ),
                (
                    "home_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "name"],
            },
        ),
    ]
