# Generated by Django 5.2.11 on 2026-02-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffschedule",
            name="simulation_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_schedules",
                to="simulation.simulationrun",
            ),
        ),
        migrations.AddField(
            model_name="staffschedule",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="company.staffmember",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffschedule",
            unique_together={("staff", "simulation_run", "day_of_week")},
        ),
    ]
